# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Blog"
url = "blog/"
weight = 3

[[main]]
weight = 4
name = "Pages"
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "Disclaimer"
  url = "disclaimer/"
  weight = 1

  [[main]]
  parent = "Pages"
  name = "Terms & Conditions"
  url = "terms-and-conditions/"
  weight = 2
  
[[main]]
name = "Contact"
url = "contact/"
weight = 5


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Blog"
url = "blog/"
weight = 2

[[footer]]
name = "Disclaimer"
url = "disclaimer/"
weight = 3

[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 4
